---
- name: install mysql server
  yum: name={{ item }} state=present
  with_items:
    - mariadb-devel
    - mariadb-server

- name: Install pip
  yum:
    name: python-pip
    update_cache: yes
    state: present

- name: install gcc
  yum: 
    name: gcc
    update_cache: yes
    state: present

- name: install mysql-python
  pip: name=mysql-python state=present

- name: create mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: start mysql service
  service: name=mariadb state=started enabled=true

